### ISSUE TITLE
elf.h file doesn't exist 

### ISSUE THREAD

**Issue by mahfouzsherif** [TheCodeArtist/elf-parser#3]
Hi,

Could you please add the elf.h file 

Thanks,

**Comment by TheCodeArtist** [comment]
The `elf.h` header is usually available in the headers packaged in your platform.

For example, on my 64bit Ubuntu 16.04 host-PC, i have 2 variants of the `elf.h` headers available at:

```
/usr/include/linux/elf.h
/usr/include/elf.h

```

**`elf-parser`** uses the `elf.h` header for the definitions of various common data-structures in the standard ELF specification.

@mahfouzsherif Which platform are you using?

**Comment by TheCodeArtist** [comment]
...also running the following command lists 474 packages on Ubuntu that contain `elf.h`
    apt-file search elf.h | awk -F":" '{print $1}' | sort -u

Most likely installing the `linux-headers-*` or `linux-libc-dev-*` packages applicable to your system should be sufficient to help get the required `elf.h` header.

**Comment by mahfouzsherif** [comment]
Thanks very reply I found the one useful for me, I am planing to use the part of that parse on windows tool to modify and update elf file
